name: Rust Release

on:
  push:
    tags:
      - '*'    

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install cargo-deb
      run: cargo install cargo-deb
    - name: Create debian package
      run: cargo deb -p hed
    - name: version
      run: echo "::set-output name=version::$(./target/release/hed --version)"
      id: version
    - name: package
      run: echo "::set-output name=package::$(basename ./target/debian/*.deb)"
      id: package
    - name: release
      uses: actions/create-release@v1
      id: create_release
      with:
        draft: false
        prerelease: false
        release_name: ${{ steps.version.outputs.version }}
        tag_name: ${{ github.ref }}
      env:
        GITHUB_TOKEN: ${{ github.token }}
    - name: upload linux artifact
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/release/hed
        asset_name: hed
        asset_content_type: application/binary
    - name: upload debian package
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./target/debian/${{ steps.package.outputs.package }}
        asset_name: ${{ steps.package.outputs.package }}
        asset_content_type: application/binary
