name: Rust

on:
  push:
    branches: [ '*','**/*' ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Install clippy
      run: rustup component add clippy
    - name: Run clippy
      run: cargo clippy -- -Dwarnings

  coverage:    
    name: coverage
    runs-on: ubuntu-latest
    container:
      image: xd009642/tarpaulin:develop-nightly
      options: --security-opt seccomp=unconfined
    steps:
      - name:                   Checkout repository
        uses:                   actions/checkout@v2
      - name:                   Generate code coverage
        run: |
          cargo tarpaulin --verbose --all-features --workspace --timeout 120 --out Xml
      - name:                   Upload to codecov.io
        uses:                   codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error:     true
